// Generated by scripts/ts_pack_ctwr_hd.py -- do not edit.
// Component tower turret pivot, canvas px from the building centre (2 leptons per px).
#pragma once
#define TSCTWR_PIVOT_EAST_PX -0.5
#define TSCTWR_PIVOT_NORTH_PX 76.8
