// GENERATED by scripts/ts_ghost_fire_points.py -- do not hand-edit.
// Ghost Stalker muzzle per HumanShape facing (0 = N, counter-clockwise), leptons from the
// unit centre: [0] standing, [1] prone.
static const short _tsghost_muzzle[2][8][2] = {
    {
        {-8, -90},  // facing 0, 3 flash stages
        {-86, -56},  // facing 1, 3 flash stages
        {-112, -23},  // facing 2, 3 flash stages
        {-89, 19},  // facing 3, 3 flash stages
        {-21, -10},  // facing 4, 3 flash stages
        {34, 12},  // facing 5, 3 flash stages
        {55, -31},  // facing 6, 3 flash stages
        {38, -68},  // facing 7, 3 flash stages
    },
    {
        {-9, -27},  // facing 0, 3 flash stages
        {-117, -10},  // facing 1, 3 flash stages
        {-140, 41},  // facing 2, 3 flash stages
        {-122, 110},  // facing 3, 3 flash stages
        {-39, 136},  // facing 4, 3 flash stages
        {77, 103},  // facing 5, 3 flash stages
        {83, 33},  // facing 6, 3 flash stages
        {47, -14},  // facing 7, 3 flash stages
    },
};
