
// GENERATED by scripts/unit_centring.py -- do not hand-edit.
// How far each unit's art was moved down to centre its hull on the unit, in leptons south.
// Fire_Coord adds it to the fire points the packers measured on the art before the move.

static const struct
{
    UnitType Type;
    short Drop;
} _unit_art_drop[] = {
    {UNIT_C3MK3, 43},
    {UNIT_C3PRED, 32},
    {UNIT_R2APOC, 40},
    {UNIT_R2PRIS, 41},
    {UNIT_TS4TNK, 39},
    {UNIT_TSAPC, 49},
    {UNIT_TSLPST, 56},
    {UNIT_TSMCV, 29},
    {UNIT_TSMEMP, 40},
    {UNIT_TSMWAR, 76},
    {UNIT_TSSAPC, 45},
    {UNIT_TSSONIC, 31},
    {UNIT_TSSUBTANK, 47},
};
