
// GENERATED by scripts/unit_centring.py -- do not hand-edit.
// How far each unit's art was moved down to centre its hull on the unit, in leptons south.
// Fire_Coord adds it to the fire points the packers measured on the art before the move.

static const struct
{
    UnitType Type;
    short Drop;
} _unit_art_drop[] = {
    {UNIT_C3MK3, 43},
    {UNIT_C3PRED, 32},
    {UNIT_R2APOC, 35},
    {UNIT_R2PRIS, 40},
    {UNIT_TS4TNK, 37},
    {UNIT_TSAPC, 48},
    {UNIT_TSLPST, 56},
    {UNIT_TSMCV, 28},
    {UNIT_TSMEMP, 35},
    {UNIT_TSMWAR, 75},
    {UNIT_TSSAPC, 45},
    {UNIT_TSSONIC, 29},
    {UNIT_TSSUBTANK, 45},
};
