#!/usr/bin/env python3
"""The Red Alert 2 easter-egg tanks, the Apocalypse (R2APOC) and the Prism Tank (R2PRIS): their
cameos, sounds and fire points. Their art is the HD rebuilds', packed by
scripts/ts_pack_hd_buildings.py: hull 0-31 + turret 32-63 (the TSSONIC layout), each tank at the
TS voxel density 6.4/12 times RA2's 48/60 cell ratio around the voxel origin at the canvas centre
(the size and place the fire points below are projected at).

Cameos: RA2's own MTNKICON / SREFICON (language.mix -> cameo.mix), decoded with the real
cameo.pal and flattened opaque (the launcher draws noise under transparent cameo pixels).

Audio: Yuri's Revenge's unit sets (langmd.mix -> audiomd.mix -> audio.bag/idx, decoded to PCM
by tools/ra2_bag_extract.py), re-encoded MS-ADPCM 22050 mono under their own R2 names. Their
sound events are hand-written in the RA2 packs' SFXEVENTSNONLOCALIZED_RA2.XML.

Cameos and WAVs land where scripts/asset_packs.py routes each name (the RA2 packs); the build
merges the packs into the mod.

Also writes redalert/r2tanks_muzzle.h: RA2's FLHs projected through the render camera per
turret frame, so shells, missiles and the prism beam leave the art's barrel tips.

Inputs (set R2_ART_DIR): raw/<sample>.wav,
ra2/{mtnkicon.shp, sreficon.shp, cameo.pal}.

License: GPL v3.
"""
import math, os, subprocess, sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ts_shp
import asset_packs

ART = os.environ.get("R2_ART_DIR")
MUZZLE_H = os.path.join(HERE, "..", "redalert", "r2tanks_muzzle.h")

# The TS voxel density 6.4/12, times RA2's cell ratio: RA2 draws voxels at TS's size onto a
# 60 px cell where TS's is 48, so its units read 0.8 as large beside a cell as TS's do.
F_VOX = 6.4 / 12 * 48 / 60
ELEV = math.radians(32)       # the renders' --elev
PX_PER_VOXEL = 12 * F_VOX     # rendered at 12 px per voxel, packed at F_VOX
LEPTONS_PER_PX = 4 / 3        # unit art: 192 canvas px to the 256-lepton cell

# name, cameo SHP
UNITS = (
    ("R2APOC", "mtnkicon.shp"),
    ("R2PRIS", "sreficon.shp"),
)

# RA2 fire points in leptons (forward, left, height). The Apocalypse's cannon is art.ini
# [MTNK] PrimaryFireFLH, mirrored for the second barrel; RA2 gives its tusks no FLH, so they
# leave the turret's side pods. The Prism's is [SREF] Weapon1FLH.
APOC_FLH = ((190, 25, 120), (-20, 70, 130))
PRIS_FLH = (48, 0, 184)

# Yuri's Revenge sample -> shipped stem. Each ships as <stem>.WAV.
SAMPLES = (
    "vaposea", "vaposeb", "vaposec", "vaposed", "vaposee",
    "vapomoa", "vapomob", "vapomoc", "vapomod", "vapomoe",
    "vapoata", "vapoatb", "vapoatc", "vapoatd", "vapoate", "vapoatf",
    "vapostaa", "vapostab", "vapostac", "vapoat1a", "vapoat2a", "vapoat2b", "vapoat2c",
    "vprisea", "vpriseb", "vprisec", "vprised", "vprisee",
    "vprimoa", "vprimob", "vprimoc", "vprimod", "vprimoe",
    "vpriata", "vpriatb", "vpriatc", "vpriatd", "vpriate",
    "vpristaa", "vpristab", "vpristac", "vpriatta",
)


def stem(sample):
    return "R2" + sample.upper()


def write_cameo(name, shp):
    cpal = ts_shp.load_pal(f"{ART}/ra2/cameo.pal")
    _, shp_frames = ts_shp.decode_shp(f"{ART}/ra2/{shp}")
    icon = ts_shp.frame_to_rgba(shp_frames[0], cpal, None, None)
    flat = Image.new("RGBA", icon.size, (0, 0, 0, 255))
    flat.alpha_composite(icon)
    big = flat.resize((flat.width * 8, flat.height * 8), Image.NEAREST).resize((341, 256), Image.LANCZOS)
    path = asset_packs.cameo_tga(f"BuildIcon_{name}")
    big.save(path)
    print(f"wrote {path}")


def write_audio():
    dirs = set()
    for s in SAMPLES:
        out_wav = asset_packs.sound_wav(stem(s))
        os.makedirs(os.path.dirname(out_wav), exist_ok=True)
        subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", f"{ART}/raw/{s}.wav",
                        "-c:a", "adpcm_ms", "-ar", "22050", "-ac", "1", out_wav], check=True)
        dirs.add(os.path.dirname(out_wav))
    print(f"wrote {len(SAMPLES)} samples to {', '.join(sorted(dirs))}")


def project(fwd, lat, hgt):
    """Per-turret-frame (east, south) leptons from the unit centre, for frame f rendered at
    yaw 90 + 11.25 f like the art."""
    rows = []
    f_v, l_v, h_v = fwd / 8.0, lat / 8.0, hgt / 8.0    # leptons to voxels
    for f in range(32):
        yaw = math.radians(90 + f * 11.25)
        rx = f_v * math.cos(yaw) - l_v * math.sin(yaw)
        ry = f_v * math.sin(yaw) + l_v * math.cos(yaw)
        x = rx * PX_PER_VOXEL
        y = -(ry * math.sin(ELEV) + h_v * math.cos(ELEV)) * PX_PER_VOXEL
        rows.append((round(x * LEPTONS_PER_PX), round(y * LEPTONS_PER_PX)))
    return rows


def rows_c(rows):
    return "{" + ", ".join(f"{{{x}, {y}}}" for x, y in rows) + "}"


def write_muzzle_header():
    hdr = "// GENERATED by scripts/r2_pack_tanks.py -- do not hand-edit.\n"
    hdr += "// RA2 tank fire points, leptons east/south of the unit centre, per turret frame.\n"
    hdr += "// Apocalypse: [weapon: cannon, tusks][side: left, right][turret frame][x, y].\n"
    hdr += "static const short _r2apoc_muzzle[2][2][32][2] = {\n"
    for fwd, lat, hgt in APOC_FLH:
        hdr += "    {\n"
        for sign in (1, -1):
            hdr += "        " + rows_c(project(fwd, sign * lat, hgt)) + ",\n"
        hdr += "    },\n"
    hdr += "};\n"
    hdr += "// Prism Tank: [turret frame][x, y].\n"
    hdr += "static const short _r2pris_muzzle[32][2] = " + rows_c(project(*PRIS_FLH)) + ";\n"
    with open(MUZZLE_H, "w") as fh:
        fh.write(hdr)
    print(f"wrote {os.path.normpath(MUZZLE_H)}")


def main():
    if not ART:
        raise SystemExit("set R2_ART_DIR (holding renders/, raw/, ra2/)")
    for name, cameo in UNITS:
        write_cameo(name, cameo)
    write_audio()
    write_muzzle_header()


if __name__ == "__main__":
    if sys.argv[1:] == ["muzzle"]:
        write_muzzle_header()
    else:
        main()
