#!/usr/bin/env python3
"""Write redalert/tspuls_muzzle.h: the EMP Cannon's barrel tip per turret frame, as the lepton
offset from the building's centre that its pulse ball charges at and fires from.

The cannon is the TSPULST layer (32 frames, CCW from north, 256 canvas on a 48 classic px
stub), drawn with its canvas centre on the building's centre lowered by TSPULS_TURRET_Y
(building.cpp). The tip of frame f is the centre of its opaque pixels furthest along that frame's screen
facing, so the table follows the art exactly and is regenerated whenever the art is.

License: GPL v3.
"""
import io, json, math, os, zipfile
from PIL import Image
import numpy as np

import asset_packs

HERE = os.path.dirname(os.path.abspath(__file__))
ZIP = asset_packs.art_zip("TSPULST", "STRUCTURES")
OUT = os.path.join(HERE, "..", "redalert", "tspuls_muzzle.h")
STUB = 48                 # classic px the canvas maps onto
TURRET_Y = 10             # classic px: building.cpp TSPULS_TURRET_Y
PITCH = 0.6               # the fleet camera's north-south foreshortening
LEPTONS_PER_CLASSIC = 256 / 24
TIP_BAND = 6              # canvas px: the tip is every pixel this close to the furthest one, so
                          # twin barrels facing the camera put the muzzle between their ends


def main():
    z = zipfile.ZipFile(ZIP)
    names = sorted(n[:-4] for n in z.namelist() if n.endswith(".tga"))
    rows = []
    for f, n in enumerate(names):
        meta = json.loads(z.read(n + ".meta"))
        W, H = meta["size"]
        a = np.array(Image.open(io.BytesIO(z.read(n + ".tga"))).convert("RGBA"))[..., 3] >= 128
        ys, xs = np.nonzero(a)
        xs = xs + meta["crop"][0] - W / 2
        ys = ys + meta["crop"][1] - H / 2
        theta = math.radians(f * 11.25)
        dx, dy = -math.sin(theta), -math.cos(theta) * PITCH
        proj = xs * dx + ys * dy
        tip = proj >= proj.max() - TIP_BAND
        k = STUB / W
        cx = xs[tip].mean() * k
        cy = ys[tip].mean() * k + TURRET_Y
        rows.append((round(cx * LEPTONS_PER_CLASSIC), round(cy * LEPTONS_PER_CLASSIC)))
    hdr = "// GENERATED by scripts/ts_emp_muzzle.py -- do not hand-edit.\n"
    hdr += "// EMP Cannon barrel tip per TSPULST frame, leptons east/south of the building centre.\n"
    hdr += "static const short _tspuls_muzzle[32][2] = {" + ", ".join(f"{{{x}, {y}}}" for x, y in rows) + "};\n"
    open(OUT, "w").write(hdr)
    print(f"wrote {os.path.normpath(OUT)}")
    for f in (0, 8, 16, 24):
        print(f"  frame {f:2}: {rows[f]}")


if __name__ == "__main__":
    main()
