#!/usr/bin/env python3
"""Measure the Ghost Stalker's muzzle per facing off the packed TS fire frames and emit
redalert/tsghost_muzzle.h: leptons from the unit's centre coordinate, standing and prone,
indexed by the HumanShape facing (0 = N, counter-clockwise).

TS draws the railgun's muzzle flash on alternate firing stages as bright yellow, brighter
than any skin tone on the sprite, so the flash is the bright warm pixels of a stage and their
centroid is the muzzle; the stages without a flash contribute nothing. The tileset canvas (267x208) is anchored by its centre at the draw point, which
the infantry Draw_It puts 2 classic px left and 4 below the unit coordinate; one HD px is
2 leptons at this scale.
"""
import io
import json
import zipfile
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ZIP = ROOT / "resources/remaster_mods/Vanilla_RA/Data/ART/TEXTURES/SRGB/RED_ALERT/UNITS/TSGHOST.ZIP"
OUT = ROOT / "redalert/tsghost_muzzle.h"
CANVAS = (267, 208)
HD_PER_CLASSIC = 128 / 24
ANCHOR = (CANVAS[0] / 2 + 2 * HD_PER_CLASSIC, CANVAS[1] / 2 - 4 * HD_PER_CLASSIC)
LEPTONS_PER_HD = (256 / 24) / HD_PER_CLASSIC
POSES = {"stand": 164, "prone": 212}   # TsE1DoControls FireUp / FireProne, 6 frames per facing


def load(zf, index):
    meta = json.loads(zf.read(f"tsghost-{index:04d}.meta"))
    tga = Image.open(io.BytesIO(zf.read(f"tsghost-{index:04d}.tga"))).convert("RGBA")
    canvas = Image.new("RGBA", CANVAS, (0, 0, 0, 0))
    canvas.alpha_composite(tga, (meta["crop"][0], meta["crop"][1]))
    return canvas.load()


def bright(p):
    return p[3] > 0 and p[0] >= 200 and p[1] >= 140 and p[2] <= 130


def flash(frames, stage):
    here = frames[stage]
    return [(x, y) for y in range(CANVAS[1]) for x in range(CANVAS[0]) if bright(here[x, y])]


def muzzle(zf, base, facing):
    frames = [load(zf, base + facing * 6 + stage) for stage in range(6)]
    found = [pts for pts in (flash(frames, stage) for stage in range(6)) if len(pts) >= 15]
    if not found:
        raise SystemExit(f"no muzzle flash found for base {base} facing {facing}")
    cx = sum(sum(x for x, _ in pts) / len(pts) for pts in found) / len(found)
    cy = sum(sum(y for _, y in pts) / len(pts) for pts in found) / len(found)
    return round((cx - ANCHOR[0]) * LEPTONS_PER_HD), round((cy - ANCHOR[1]) * LEPTONS_PER_HD), len(found)


def main():
    with zipfile.ZipFile(ZIP) as zf:
        tables = {pose: [muzzle(zf, base, f) for f in range(8)] for pose, base in POSES.items()}
    lines = ["// GENERATED by scripts/ts_ghost_fire_points.py -- do not hand-edit.",
             "// Ghost Stalker muzzle per HumanShape facing (0 = N, counter-clockwise), leptons from the",
             "// unit centre: [0] standing, [1] prone.",
             "static const short _tsghost_muzzle[2][8][2] = {"]
    for pose in ("stand", "prone"):
        lines.append("    {")
        for f, (dx, dy, n) in enumerate(tables[pose]):
            lines.append(f"        {{{dx}, {dy}}},  // facing {f}, {n} flash stages")
        lines.append("    },")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n")
    for pose in ("stand", "prone"):
        print(pose, [(dx, dy) for dx, dy, _ in tables[pose]])
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
