#!/usr/bin/env python3
"""Fire points of the Mammoth Mk. II, read off its HD model (asset-packs/TS-HD-Graphics-Pack/3d/mammoth-mk2.glb).

The railgun fires from the fronts of the two side pods and the missiles from the faces of the two rear pods,
left and right shot by shot, as Westwood's FMVs show it. Each mouth is projected through the art's camera for
the 32 hull facings and written to redalert/tshmec_muzzle.h as leptons east and south of the unit's position.

Usage: ts_hmec_muzzle.py [--check FRAME_DIR OUT_PNG]   (--check marks the points on the packed frames)
License: GPL v3.
"""
import json, math, os, struct, sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
GLB = os.path.join(HERE, "..", "asset-packs", "TS-HD-Graphics-Pack", "3d", "mammoth-mk2.glb")
HEADER = os.path.join(HERE, "..", "redalert", "tshmec_muzzle.h")

# The art's camera (resources/custom-art/ts-units-hd/tshmec/README.txt): 35 degrees above the ground, 192 canvas
# px to the cell, the unit's position at (287.5, 374) on the 576 canvas, whose centre the game puts on the unit.
ELEV = math.radians(35)
PX_PER_CELL = 192
ORIGIN = (287.5, 374.0)
CENTRE = (288.0, 288.0)
LEPTONS_PER_PX = 256 / PX_PER_CELL

# weapon -> (left mesh, right mesh, which face): the model faces east, so its right is +z (south).
MOUTHS = (("spod_tubes_2", "spod_tubes", "front"), ("rpod_tubes_2", "rpod_tubes", "front"))


def glb_nodes(path):
    """Each named mesh node's vertices in model space (x east, y up, z south; 1.0 = one cell)."""
    data = open(path, "rb").read()
    json_len = struct.unpack("<I", data[12:16])[0]
    gltf = json.loads(data[20:20 + json_len])
    off = 20 + json_len
    binary = data[off + 8:off + 8 + struct.unpack("<I", data[off:off + 4])[0]]
    nodes = gltf["nodes"]
    parent = {c: i for i, n in enumerate(nodes) for c in n.get("children", [])}

    def local(n):
        if "matrix" in n:
            return np.array(n["matrix"], float).reshape(4, 4).T
        m = np.diag(list(n.get("scale", [1, 1, 1])) + [1])
        if "rotation" in n:
            x, y, z, w = n["rotation"]
            r = np.eye(4)
            r[:3, :3] = [[1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
                         [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
                         [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)]]
            m = r @ m
        t = np.eye(4)
        t[:3, 3] = n.get("translation", [0, 0, 0])
        return t @ m

    out = {}
    for i, n in enumerate(nodes):
        if "mesh" not in n:
            continue
        m, j = local(n), i
        while j in parent:
            j = parent[j]
            m = local(nodes[j]) @ m
        pts = []
        for prim in gltf["meshes"][n["mesh"]]["primitives"]:
            acc = gltf["accessors"][prim["attributes"]["POSITION"]]
            view = gltf["bufferViews"][acc["bufferView"]]
            stride = view.get("byteStride", 12) // 4
            arr = np.frombuffer(binary, np.float32, acc["count"] * stride,
                                view.get("byteOffset", 0) + acc.get("byteOffset", 0)).reshape(-1, stride)[:, :3]
            pts.append(arr)
        p = np.vstack(pts)
        out[n.get("name", "")] = (np.c_[p, np.ones(len(p))] @ m.T)[:, :3]
    return out


def mouth(points):
    """Centre of a pod's front face: its forward-most vertices, mid height and mid width."""
    front = points[points[:, 0] >= points[:, 0].max() - 0.01]
    return front[:, 0].max(), (front[:, 1].min() + front[:, 1].max()) / 2, (front[:, 2].min() + front[:, 2].max()) / 2


def canvas_point(fwd, up, right, facing):
    """A model point on the 576 canvas for hull frame `facing` (counter-clockwise from north)."""
    a = math.radians(((32 - facing) % 32) * 11.25)
    east = fwd * math.sin(a) + right * math.cos(a)
    south = -fwd * math.cos(a) + right * math.sin(a)
    return (ORIGIN[0] + east * PX_PER_CELL,
            ORIGIN[1] + (south * math.sin(ELEV) - up * math.cos(ELEV)) * PX_PER_CELL)


def table():
    """[weapon][side][facing] -> canvas (x, y)."""
    nodes = glb_nodes(GLB)
    out = []
    for left, right, _ in MOUTHS:
        sides = []
        for name in (left, right):
            fwd, up, side = mouth(nodes[name])
            sides.append([canvas_point(fwd, up, side, f) for f in range(32)])
        out.append(sides)
    return out


def write_header(t):
    lines = ["// GENERATED by scripts/ts_hmec_muzzle.py from the Mammoth Mk. II's HD model; do not hand-edit.",
             "// Fire points, leptons east/south of the unit's position: [weapon: railgun, missiles]",
             "// [side: left, right][hull frame][x, y].",
             "static const short _tshmec_muzzle[2][2][32][2] = {"]
    for sides in t:
        lines.append("    {")
        for rows in sides:
            cells = ", ".join(f"{{{round((x - CENTRE[0]) * LEPTONS_PER_PX)}, {round((y - CENTRE[1]) * LEPTONS_PER_PX)}}}"
                              for x, y in rows)
            lines.append(f"        {{{cells}}},")
        lines.append("    },")
    lines.append("};")
    with open(HEADER, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.relpath(HEADER)}")


def check(t, frame_dir, out_png):
    """Mark every fire point on the source frames (step 0) of every 4th facing."""
    from PIL import Image, ImageDraw
    tiles = []
    for f in range(0, 32, 4):
        im = Image.open(os.path.join(frame_dir, f"tshmec-{f * 8:04d}.png")).convert("RGBA")
        bg = Image.new("RGBA", im.size, (90, 100, 80, 255))
        bg.alpha_composite(im)
        d = ImageDraw.Draw(bg)
        for w, colour in enumerate(((60, 160, 255, 255), (255, 80, 40, 255))):
            for s in range(2):
                x, y = t[w][s][f]
                d.ellipse((x - 5, y - 5, x + 5, y + 5), outline=colour, width=2)
        d.text((6, 6), f"facing {f}", fill=(255, 255, 255, 255))
        tiles.append(bg.crop((96, 96, 480, 480)))
    sheet = Image.new("RGBA", (384 * 4, 384 * 2))
    for i, tile in enumerate(tiles):
        sheet.paste(tile, ((i % 4) * 384, (i // 4) * 384))
    sheet.save(out_png)
    print(f"wrote {out_png}")


if __name__ == "__main__":
    t = table()
    if sys.argv[1:2] == ["--check"]:
        check(t, sys.argv[2], sys.argv[3])
    else:
        write_header(t)
