#!/usr/bin/env python3
"""Package the old TS Mammoth Tank (TS [4TNK], TechLevel -1 in TS) as TS4TNK.

TS4TNK.ZIP is 64 frames: hull 0-31 + turret 32-63 (the TSSONIC layout), on a 448
canvas (ShapeSize 56), each render scaled by the TS voxel density 6.4/12 around the
voxel origin at the canvas centre (the vox_frames recipe in ts_pack_units_wave.py).
The turret renders carry the barrel in the same depth-sorted pass (vxl_render.py
--attach), so it hides and is hidden correctly at every facing. Also writes the
RA_UNITS.XML tile run and the cannon + tusk reports under their own names.

Renders (the voxel ledger in docs/launcher-render-contracts.md, one canvas for both):
  vxl_render.py 4TNK.VXL    renders_4tnk    --frames 32 --yaw0 90 --px-per-voxel 12
      --team-green 0,139,0 --elev 32 --hva 4TNK.HVA --canvas 720
  vxl_render.py 4TNKTUR.VXL renders_4tnktur (same) --hva 4TNKTUR.HVA
      --attach 4TNKBARL.VXL --attach-hva 4TNKBARL.HVA
TS painted 77% of this hull in remap (the Disruptor: 24%), and its remap voxels are
brighter than the fleet's, so the fleet's 0,200,0 would clip it. 0,139,0 puts its team
pixels at the APC's median brightness, so it wears the same team colour as the APC. The
hull keeps TS's all-team look.
Follow with scripts/ts_reshadow.py TS4TNK.

Also writes redalert/ts4tnk_muzzle.h, the per-frame fire points Fire_Coord reads: TS's
FLHs projected through the same camera, so the shells and tusk missiles leave the barrel
tips and pods the art shows. `ts_pack_4tnk.py muzzle` writes only the header: it reads no
art, though TS_ART_DIR must still be set for the shared packer import.

Inputs (set TS_ART_DIR): $TS_ART_DIR/renders_4tnk*, $TS_ART_DIR/.raw/{120MMX9,MISL1}.AUD.

License: GPL v3.
"""
import math, os, subprocess, sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from ts_pack_pods import ART, MOD, RAW, write_zip, patch_tileset

UNITS_DIR = f"{MOD}/ART/TEXTURES/SRGB/RED_ALERT/UNITS"
UNITS_XML = f"{MOD}/XML/TILESETS/RA_UNITS.XML"
CANVAS = 448
F_VOX = 6.4 / 12
def vox_frames(dirname):
    out = []
    for i in range(32):
        im = Image.open(f"{ART}/{dirname}/frame-{i:04d}.png").convert("RGBA")
        scaled = im.resize((round(im.width * F_VOX), round(im.height * F_VOX)), Image.LANCZOS)
        fr = Image.new("RGBA", (CANVAS, CANVAS), (0, 0, 0, 0))
        ox, oy = round(CANVAS / 2 - scaled.width / 2), round(CANVAS / 2 - scaled.height / 2)
        b = scaled.getbbox()
        if b and (ox + b[0] < 0 or oy + b[1] < 0 or ox + b[2] > CANVAS or oy + b[3] > CANVAS):
            raise SystemExit(f"{dirname} frame {i}: content clipped -- grow the canvas")
        fr.alpha_composite(scaled, (max(ox, 0), max(oy, 0)))
        out.append(fr)
    return out


# TS [4TNK] fire points in TS leptons (forward, left, height): the cannon's fire point
# carried out along the barrel to its tip, and the tusk pods.
FLH = ((40 + 192, 32, 96), (-32, 80, 120))
ELEV = math.radians(32)       # the renders' --elev
PX_PER_VOXEL = 12 * F_VOX     # rendered at 12 px per voxel, packed at F_VOX
LEPTONS_PER_PX = 4 / 3        # unit art: 192 canvas px to the 256-lepton cell
MUZZLE_H = os.path.join(HERE, "..", "redalert", "ts4tnk_muzzle.h")


def muzzle_table():
    """[weapon][side][frame] -> (east, south) leptons from the unit centre.

    Weapon 0 is the cannon, 1 the tusks; side 0 is the turret's left, 1 its right.
    Frame f is turret frame f, rendered at yaw 90 + 11.25 f like the art."""
    out = []
    for fwd, lat, hgt in FLH:
        sides = []
        for sign in (1, -1):
            rows = []
            f_v, l_v, h_v = fwd / 8.0, sign * lat / 8.0, hgt / 8.0    # TS leptons to voxels
            for f in range(32):
                yaw = math.radians(90 + f * 11.25)
                rx = f_v * math.cos(yaw) - l_v * math.sin(yaw)
                ry = f_v * math.sin(yaw) + l_v * math.cos(yaw)
                x = rx * PX_PER_VOXEL
                y = -(ry * math.sin(ELEV) + h_v * math.cos(ELEV)) * PX_PER_VOXEL
                rows.append((round(x * LEPTONS_PER_PX), round(y * LEPTONS_PER_PX)))
            sides.append(rows)
        out.append(sides)
    return out


def write_muzzle_header():
    hdr = "// GENERATED by scripts/ts_pack_4tnk.py -- do not hand-edit.\n"
    hdr += "// Mammoth Mk. I fire points, leptons east/south of the unit centre:\n"
    hdr += "// [weapon: cannon, tusks][side: left, right][turret frame][x, y].\n"
    hdr += "static const short _ts4tnk_muzzle[2][2][32][2] = {\n"
    for sides in muzzle_table():
        hdr += "    {\n"
        for rows in sides:
            hdr += "        {" + ", ".join(f"{{{x}, {y}}}" for x, y in rows) + "},\n"
        hdr += "    },\n"
    hdr += "};\n"
    with open(MUZZLE_H, "w") as fh:
        fh.write(hdr)
    print(f"wrote {os.path.normpath(MUZZLE_H)}")


def main():
    frames = vox_frames("renders_4tnk") + vox_frames("renders_4tnktur")
    write_zip(f"{UNITS_DIR}/TS4TNK.ZIP", "ts4tnk", frames)
    patch_tileset(UNITS_XML, "TS4TNK", len(frames))
    for aud in ("120MMX9", "MISL1"):
        pcm = f"{RAW}/{aud}.pcm.wav"
        out_wav = f"{MOD}/AUDIO/TS{aud}.WAV"
        subprocess.run([sys.executable, f"{HERE}/ts_aud_decode.py", f"{RAW}/{aud}.AUD", pcm],
                       check=True, stdout=subprocess.DEVNULL)
        subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", pcm,
                        "-c:a", "adpcm_ms", "-ar", "22050", "-ac", "1", out_wav], check=True)
        print(f"wrote {out_wav}")
    write_muzzle_header()


if __name__ == "__main__":
    if sys.argv[1:] == ["muzzle"]:
        write_muzzle_header()
    else:
        main()
