#!/usr/bin/env python3
"""The old TS Mammoth Tank (TS [4TNK], TechLevel -1 in TS) as TS4TNK: its cannon and tusk sounds
and its fire points. Its art is the HD rebuild's, packed by scripts/ts_pack_hd_buildings.py: 64
frames, hull 0-31 + turret 32-63, on a 512 canvas with the voxel origin at the centre, at the TS
voxel density 6.4/12 (the size the fire points below are projected at).

Writes redalert/ts4tnk_muzzle.h, the per-frame fire points Fire_Coord reads: TS's
FLHs projected through the same camera, so the shells and tusk missiles leave the barrel
tips and pods the art shows. `ts_pack_4tnk.py muzzle` writes only the header; TS_ART_DIR must
still be set for the shared packer import.

Inputs (set TS_ART_DIR): $TS_ART_DIR/.raw/{120MMX9,MISL1}.AUD.

License: GPL v3.
"""
import math, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import asset_packs
from ts_pack_pods import RAW

# The TS voxel density 6.4/12 draws the Mk. I at the RA Mammoth Tank's size (34.6 x 24.4
# classic px, measured off EA's 4TNK).
F_VOX = 6.4 / 12


# TS [4TNK] fire points in TS leptons (forward, left, height): the cannon's fire point
# carried out along the barrel to its tip, and the tusk pods.
FLH = ((40 + 192, 32, 96), (-32, 80, 120))
ELEV = math.radians(32)       # the renders' --elev
PX_PER_VOXEL = 12 * F_VOX     # rendered at 12 px per voxel, packed at F_VOX
LEPTONS_PER_PX = 4 / 3        # unit art: 192 canvas px to the 256-lepton cell
MUZZLE_H = os.path.join(HERE, "..", "redalert", "ts4tnk_muzzle.h")


def muzzle_table():
    """[weapon][side][frame] -> (east, south) leptons from the unit centre.

    Weapon 0 is the cannon, 1 the tusks; side 0 is the turret's left, 1 its right.
    Frame f is turret frame f, rendered at yaw 90 + 11.25 f like the art."""
    out = []
    for fwd, lat, hgt in FLH:
        sides = []
        for sign in (1, -1):
            rows = []
            f_v, l_v, h_v = fwd / 8.0, sign * lat / 8.0, hgt / 8.0    # TS leptons to voxels
            for f in range(32):
                yaw = math.radians(90 + f * 11.25)
                rx = f_v * math.cos(yaw) - l_v * math.sin(yaw)
                ry = f_v * math.sin(yaw) + l_v * math.cos(yaw)
                x = rx * PX_PER_VOXEL
                y = -(ry * math.sin(ELEV) + h_v * math.cos(ELEV)) * PX_PER_VOXEL
                rows.append((round(x * LEPTONS_PER_PX), round(y * LEPTONS_PER_PX)))
            sides.append(rows)
        out.append(sides)
    return out


def write_muzzle_header():
    hdr = "// GENERATED by scripts/ts_pack_4tnk.py -- do not hand-edit.\n"
    hdr += "// Mammoth Mk. I fire points, leptons east/south of the unit centre:\n"
    hdr += "// [weapon: cannon, tusks][side: left, right][turret frame][x, y].\n"
    hdr += "static const short _ts4tnk_muzzle[2][2][32][2] = {\n"
    for sides in muzzle_table():
        hdr += "    {\n"
        for rows in sides:
            hdr += "        {" + ", ".join(f"{{{x}, {y}}}" for x, y in rows) + "},\n"
        hdr += "    },\n"
    hdr += "};\n"
    with open(MUZZLE_H, "w") as fh:
        fh.write(hdr)
    print(f"wrote {os.path.normpath(MUZZLE_H)}")


def main():
    for aud in ("120MMX9", "MISL1"):
        pcm = f"{RAW}/{aud}.pcm.wav"
        out_wav = asset_packs.sound_wav(f"TS{aud}")
        subprocess.run([sys.executable, f"{HERE}/ts_aud_decode.py", f"{RAW}/{aud}.AUD", pcm],
                       check=True, stdout=subprocess.DEVNULL)
        subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", pcm,
                        "-c:a", "adpcm_ms", "-ar", "22050", "-ac", "1", out_wav], check=True)
        print(f"wrote {out_wav}")
    write_muzzle_header()


if __name__ == "__main__":
    if sys.argv[1:] == ["muzzle"]:
        write_muzzle_header()
    else:
        main()
