#!/usr/bin/env python3
"""Write redalert/tsttnk_muzzle.h: the Tick Tank's gun tip per turret facing, from the HD art's muzzle tables.

  _tsttnk_muzzle  the tank (resources/custom-art/ts-units-hd/tsttnk/muzzle.txt): leptons from the unit's
                  position, its turret frames on the 384 canvas drawn at 8 canvas px a classic px
  _tstick_muzzle  dug in (resources/custom-art/ts-buildings-hd/tstick/muzzle.txt): leptons from the cell's
                  centre, its turret frames on the 256 canvas at 128 px a cell

Both are screen offsets (south includes the height), indexed by the turret frame: 0 north, anticlockwise.
Usage: ts_ttnk_muzzle.py
License: GPL v3.
"""
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
UNIT = os.path.join(ROOT, "resources", "custom-art", "ts-units-hd", "tsttnk", "muzzle.txt")
DUG_IN = os.path.join(ROOT, "resources", "custom-art", "ts-buildings-hd", "tstick", "muzzle.txt")
HEADER = os.path.join(ROOT, "redalert", "tsttnk_muzzle.h")


def rows(path, first_frame):
    """(frame, x, y) canvas px for each table row, the frame counted from first_frame."""
    out = {}
    for line in open(path):
        nums = re.findall(r"-?\d+(?:\.\d+)?", line)
        if len(nums) < 4 or not re.match(r"\s*\d+\s+\d+", line):
            continue
        frame = int(nums[0]) - first_frame
        if 0 <= frame < 32:
            out[frame] = (float(nums[2]), float(nums[3]))
    assert len(out) == 32, f"{path}: {len(out)} rows"
    return [out[f] for f in range(32)]


def table(name, points, centre, leptons_per_px, comment):
    body = ",\n".join(f"    {{{round((x - centre[0]) * leptons_per_px)}, {round((y - centre[1]) * leptons_per_px)}}}"
                      for x, y in points)
    return f"// {comment}\nstatic const short {name}[32][2] = {{\n{body}\n}};\n"


def main():
    unit = rows(UNIT, 32)
    dug_in = rows(DUG_IN, 0)
    text = ("// GENERATED by scripts/ts_ttnk_muzzle.py from the Tick Tank's HD muzzle tables; do not hand-edit.\n"
            "// The gun's tip per turret frame (0 north, anticlockwise), leptons east and south on screen.\n"
            + table("_tsttnk_muzzle", unit, (192, 192), 256 / 24 / 8, "The tank: from the unit's position.")
            + table("_tstick_muzzle", dug_in, (128, 128), 256 / 128, "Dug in: from the cell's centre."))
    open(HEADER, "w").write(text)
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
